version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Map container's port 3000 to host's port 3000
    environment:
      NODE_ENV: development
    volumes:
      - .:/app # Mount the current directory to the container's /app
    command: npm run dev # Run the development server
